-- AcademicAI schema (PostgreSQL dialect): migration 1, the baseline.
--
-- The same tables, columns, constraints and indexes as schema.sql, which
-- remains the SQLite schema and the place each column's meaning is explained.
-- Only the dialect differs:
--   * ids are BIGINT identity columns, and every column holding an id is BIGINT
--   * tables are created in foreign-key order (a table after those it references)
--   * plain CREATE: this runs exactly once, from db/postgres.py's migration
--     runner, which records it in schema_migrations. Later changes are new
--     files in db/migrations_postgres/ (0002_*.sql, ...), never edits here.
-- Types are kept as they are in SQLite on purpose: timestamps, dates and times
-- stay ISO-8601 TEXT (the application compares them as strings) and flags stay
-- INTEGER 0/1 (the application writes and compares 0 and 1).

CREATE TABLE universities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    created_at  TEXT NOT NULL,
    -- The university's academic clock: a geographic IANA zone ('Africa/Lagos').
    timezone    TEXT NOT NULL
);

CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name         TEXT NOT NULL,
    email             TEXT NOT NULL UNIQUE,
    password_hash     TEXT NOT NULL,
    email_verified    INTEGER NOT NULL DEFAULT 0,
    email_verification_method TEXT,
    -- LEGACY, UNREAD (see schema.sql). Must NOT be treated as a gate.
    identity_status   TEXT NOT NULL DEFAULT 'UNVERIFIED'
                      CHECK (identity_status IN ('UNVERIFIED','NEEDS_REVIEW','VERIFIED','REJECTED')),
    token_epoch       INTEGER NOT NULL DEFAULT 1,
    university_id     BIGINT REFERENCES universities(id),
    department        TEXT,
    level             TEXT,
    academic_session  TEXT,
    student_id_number TEXT,
    terms_version     TEXT,
    terms_accepted_at TEXT,
    created_at        TEXT NOT NULL,
    updated_at        TEXT NOT NULL
);
CREATE INDEX idx_users_email ON users(email);

CREATE TABLE university_email_domains (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id   BIGINT NOT NULL REFERENCES universities(id),
    domain          TEXT NOT NULL UNIQUE,
    domain_type     TEXT NOT NULL DEFAULT 'STUDENT'
                    CHECK (domain_type IN ('STUDENT', 'INSTITUTIONAL')),
    active          INTEGER NOT NULL DEFAULT 1,
    created_at      TEXT NOT NULL,
    deactivated_at  TEXT
);
CREATE INDEX idx_uni_domains_lookup ON university_email_domains(domain, active);
CREATE INDEX idx_uni_domains_university ON university_email_domains(university_id, active);

CREATE TABLE academic_communities (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id     BIGINT NOT NULL REFERENCES universities(id),
    department        TEXT NOT NULL,
    level             TEXT NOT NULL,
    academic_session  TEXT NOT NULL,
    status            TEXT NOT NULL DEFAULT 'PENDING'
                      CHECK (status IN ('PENDING','ACTIVE','ARCHIVED')),
    created_at        TEXT NOT NULL,
    updated_at        TEXT NOT NULL,
    UNIQUE (university_id, department, level, academic_session)
);

CREATE TABLE community_members (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id  BIGINT NOT NULL REFERENCES academic_communities(id),
    user_id       BIGINT NOT NULL REFERENCES users(id),
    role          TEXT NOT NULL DEFAULT 'STUDENT'
                  CHECK (role IN ('STUDENT','VERIFIED_REP')),
    status        TEXT NOT NULL DEFAULT 'PENDING_APPROVAL'
                  CHECK (status IN ('PENDING_APPROVAL','ACTIVE','REJECTED','ENDED')),
    requested_at  TEXT NOT NULL,
    approved_by   BIGINT REFERENCES users(id),
    approved_at   TEXT,
    ended_at      TEXT,
    rep_since     TEXT,
    UNIQUE (community_id, user_id)
);
-- At most one ACTIVE membership per user, enforced by the database.
CREATE UNIQUE INDEX idx_one_active_membership_per_user
    ON community_members(user_id) WHERE status = 'ACTIVE';
CREATE INDEX idx_members_community ON community_members(community_id, status);
CREATE INDEX idx_members_user ON community_members(user_id, status);

-- LEGACY, UNWRITTEN (see schema.sql). Kept so the two schemas stay the same.
CREATE TABLE identity_verifications (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users(id),
    status         TEXT NOT NULL
                   CHECK (status IN ('NEEDS_REVIEW','VERIFIED','REJECTED')),
    provider       TEXT,
    authoritative  INTEGER NOT NULL DEFAULT 0,
    evidence_format TEXT,
    evidence_width  INTEGER,
    evidence_height INTEGER,
    evidence_bytes  BIGINT,
    evidence_deleted_at TEXT,
    submitted_at   TEXT NOT NULL,
    reviewed_at    TEXT,
    reviewer_note  TEXT
);
CREATE INDEX idx_identity_user ON identity_verifications(user_id);

CREATE TABLE sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    token_hash  TEXT NOT NULL UNIQUE,
    token_epoch INTEGER NOT NULL,
    created_at  TEXT NOT NULL,
    expires_at  TEXT NOT NULL,
    revoked_at  TEXT
);
CREATE INDEX idx_sessions_user ON sessions(user_id);

CREATE TABLE email_verification_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    token_hash  TEXT NOT NULL UNIQUE,
    code_salt   TEXT,
    attempts    INTEGER NOT NULL DEFAULT 0,
    expires_at  TEXT NOT NULL,
    used_at     TEXT,
    created_at  TEXT NOT NULL
);

CREATE TABLE password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    token_hash  TEXT NOT NULL UNIQUE,
    expires_at  TEXT NOT NULL,
    used_at     TEXT,
    created_at  TEXT NOT NULL
);

CREATE TABLE courses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id  BIGINT NOT NULL REFERENCES academic_communities(id),
    code          TEXT NOT NULL,
    title         TEXT,
    status        TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','REMOVED')),
    version       INTEGER NOT NULL DEFAULT 1,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    UNIQUE (community_id, code)
);

CREATE TABLE course_enrollments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id   BIGINT NOT NULL REFERENCES courses(id),
    user_id     BIGINT NOT NULL REFERENCES users(id),
    status      TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DROPPED')),
    created_at  TEXT NOT NULL,
    UNIQUE (course_id, user_id)
);
CREATE INDEX idx_enrollments_course ON course_enrollments(course_id, status);

CREATE TABLE timetable_entries (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id  BIGINT NOT NULL REFERENCES academic_communities(id),
    course_id     BIGINT REFERENCES courses(id),
    title         TEXT,
    day_of_week   TEXT NOT NULL
                  CHECK (day_of_week IN ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')),
    start_time    TEXT,
    end_time      TEXT,
    venue         TEXT,
    status        TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','CANCELLED')),
    version       INTEGER NOT NULL DEFAULT 1,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);
CREATE INDEX idx_timetable_community ON timetable_entries(community_id, status);

CREATE TABLE academic_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id    BIGINT NOT NULL REFERENCES academic_communities(id),
    course_id       BIGINT REFERENCES courses(id),
    event_type      TEXT NOT NULL
                    CHECK (event_type IN ('ASSIGNMENT','PROJECT','QUIZ','TEST','PRESENTATION','EXAM','CLASS','OTHER')),
    title           TEXT NOT NULL,
    description     TEXT,
    -- NULL means explicitly unspecified; that is not an AI failure (spec 14).
    event_date      TEXT,
    event_time      TEXT,
    venue           TEXT,
    priority        TEXT NOT NULL DEFAULT 'NORMAL' CHECK (priority IN ('LOW','NORMAL','HIGH')),
    status          TEXT NOT NULL DEFAULT 'SCHEDULED'
                    CHECK (status IN ('SCHEDULED','CANCELLED','RESCHEDULED')),
    original_message TEXT,
    version         INTEGER NOT NULL DEFAULT 1,
    created_by      BIGINT NOT NULL REFERENCES users(id),
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);
CREATE INDEX idx_events_community ON academic_events(community_id, status);
CREATE INDEX idx_events_course ON academic_events(course_id);

CREATE TABLE event_attachments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       BIGINT NOT NULL REFERENCES academic_events(id),
    storage_key    TEXT NOT NULL UNIQUE,
    original_name  TEXT NOT NULL,
    content_type   TEXT NOT NULL,
    byte_size      BIGINT NOT NULL,
    checksum       TEXT,
    status         TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','REMOVED')),
    uploaded_by    BIGINT NOT NULL REFERENCES users(id),
    created_at     TEXT NOT NULL,
    removed_by     BIGINT REFERENCES users(id),
    removed_at     TEXT
);
CREATE INDEX idx_attachments_event ON event_attachments(event_id, status);

CREATE TABLE announcements (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id     BIGINT NOT NULL REFERENCES academic_communities(id),
    title            TEXT NOT NULL,
    body             TEXT NOT NULL,
    original_message TEXT,
    status           TEXT NOT NULL DEFAULT 'PUBLISHED' CHECK (status IN ('PUBLISHED','WITHDRAWN')),
    version          INTEGER NOT NULL DEFAULT 1,
    created_by       BIGINT NOT NULL REFERENCES users(id),
    created_at       TEXT NOT NULL,
    updated_at       TEXT NOT NULL
);
CREATE INDEX idx_announcements_community ON announcements(community_id, status);

CREATE TABLE rep_nominations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id  BIGINT NOT NULL REFERENCES academic_communities(id),
    user_id       BIGINT NOT NULL REFERENCES users(id),
    nominated_by  BIGINT NOT NULL REFERENCES users(id),
    status        TEXT NOT NULL DEFAULT 'OPEN'
                  CHECK (status IN ('OPEN','PASSED','FAILED','CANCELLED')),
    opened_at     TEXT NOT NULL,
    closes_at     TEXT NOT NULL,
    resolved_at   TEXT,
    yes_votes     INTEGER,
    no_votes      INTEGER
);
CREATE INDEX idx_nominations_open ON rep_nominations(status, closes_at);
CREATE INDEX idx_nominations_community ON rep_nominations(community_id, user_id);

CREATE TABLE rep_verification_votes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomination_id  BIGINT NOT NULL REFERENCES rep_nominations(id),
    voter_id       BIGINT NOT NULL REFERENCES users(id),
    vote           TEXT NOT NULL CHECK (vote IN ('YES','NO')),
    created_at     TEXT NOT NULL,
    UNIQUE (nomination_id, voter_id)
);

CREATE TABLE rep_removals (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id    BIGINT NOT NULL REFERENCES academic_communities(id),
    target_user_id  BIGINT NOT NULL REFERENCES users(id),
    initiated_by    BIGINT NOT NULL REFERENCES users(id),
    status          TEXT NOT NULL DEFAULT 'OPEN'
                    CHECK (status IN ('OPEN','PASSED','FAILED')),
    opened_at       TEXT NOT NULL,
    closes_at       TEXT NOT NULL,
    resolved_at     TEXT,
    yes_votes       INTEGER,
    no_votes        INTEGER
);
CREATE INDEX idx_removals_open ON rep_removals(status, closes_at);
CREATE INDEX idx_removals_target ON rep_removals(community_id, target_user_id);

CREATE TABLE rep_removal_votes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    removal_id  BIGINT NOT NULL REFERENCES rep_removals(id),
    voter_id    BIGINT NOT NULL REFERENCES users(id),
    vote        TEXT NOT NULL CHECK (vote IN ('YES','NO')),
    created_at  TEXT NOT NULL,
    UNIQUE (removal_id, voter_id)
);

CREATE TABLE academic_calendars (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id   BIGINT NOT NULL REFERENCES academic_communities(id),
    uploaded_by    BIGINT NOT NULL REFERENCES users(id),
    raw_text       TEXT NOT NULL,
    session_start  TEXT,
    session_end    TEXT,
    extracted      TEXT,
    created_at     TEXT NOT NULL
);

CREATE TABLE change_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id    BIGINT NOT NULL REFERENCES academic_communities(id),
    entity_type     TEXT NOT NULL,
    entity_id       BIGINT NOT NULL,
    change_type     TEXT NOT NULL,
    old_value       TEXT,
    new_value       TEXT,
    actor_id        BIGINT REFERENCES users(id),
    source_message  TEXT,
    context         TEXT,
    created_at      TEXT NOT NULL
);
CREATE INDEX idx_history_entity ON change_history(entity_type, entity_id);
CREATE INDEX idx_history_community ON change_history(community_id, created_at);

CREATE TABLE personal_reminders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id),
    event_id     BIGINT REFERENCES academic_events(id),
    title        TEXT NOT NULL,
    remind_at    TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'PENDING'
                 CHECK (status IN ('PENDING','SENT','CANCELLED')),
    created_at   TEXT NOT NULL,
    sent_at      TEXT
);
CREATE INDEX idx_personal_reminders_due ON personal_reminders(status, remind_at);

CREATE TABLE personal_event_completions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id),
    event_id      BIGINT NOT NULL REFERENCES academic_events(id),
    completed_at  TEXT NOT NULL,
    UNIQUE (user_id, event_id)
);

CREATE TABLE event_reminders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    BIGINT NOT NULL REFERENCES academic_events(id),
    remind_at   TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'PENDING'
                CHECK (status IN ('PENDING','SENT','CANCELLED')),
    created_at  TEXT NOT NULL,
    sent_at     TEXT
);
CREATE INDEX idx_event_reminders_due ON event_reminders(status, remind_at);
CREATE INDEX idx_event_reminders_event ON event_reminders(event_id, status);

-- Email outbox and in-app notifications (see schema.sql). dedupe_key's UNIQUE
-- constraint is what notification_service's ON CONFLICT (dedupe_key) names.
CREATE TABLE notifications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id),
    community_id  BIGINT REFERENCES academic_communities(id),
    subject       TEXT NOT NULL,
    body          TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'PENDING'
                  CHECK (status IN ('PENDING','SENT','SIMULATED','FAILED')),
    attempts      INTEGER NOT NULL DEFAULT 0,
    last_error    TEXT,
    dedupe_key    TEXT UNIQUE,
    created_at    TEXT NOT NULL,
    sent_at       TEXT,
    kind          TEXT,
    link          TEXT,
    read_at       TEXT,
    app_subject   TEXT,
    app_body      TEXT
);
CREATE INDEX idx_notifications_pending ON notifications(status, id);
CREATE INDEX idx_notifications_user ON notifications(user_id, id DESC);

CREATE TABLE chat_conversations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id),
    community_id  BIGINT NOT NULL REFERENCES academic_communities(id),
    title         TEXT,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);
CREATE INDEX idx_chat_conv_user ON chat_conversations(user_id, updated_at);

CREATE TABLE chat_messages (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT NOT NULL REFERENCES chat_conversations(id),
    role             TEXT NOT NULL CHECK (role IN ('user','assistant')),
    content          TEXT NOT NULL,
    created_at       TEXT NOT NULL
);
CREATE INDEX idx_chat_msg_conv ON chat_messages(conversation_id, id);
